# Generated by Django 5.0.6 on 2024-05-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Employee_id',
            new_name='Employee_ID',
        ),
    ]
