# Generated by Django 5.0.6 on 2024-05-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_employee_id_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_ID',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
