# Generated by Django 5.0.6 on 2024-05-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(auto_created=True)),
                ('Event_Type', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Venue', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
