# Generated by Django 5.0.6 on 2024-05-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Event_Type',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Venue',
            new_name='venue',
        ),
    ]
