# Generated by Django 5.0.6 on 2024-06-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0006_report_approved_report_approved_at_report_assignment_and_more'),
        ('employee', '0005_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
            preserve_default=False,
        ),
    ]
