# Generated by Django 5.0.6 on 2024-06-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0007_assignment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='message',
            field=models.TextField(default='make sure to submit a report', max_length=225),
        ),
    ]
