# Generated by Django 5.0.6 on 2024-06-14 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0008_assignment_message'),
        ('employee', '0005_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Notes',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='report',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='report',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='report',
            name='event',
        ),
        migrations.RemoveField(
            model_name='report',
            name='proof',
        ),
        migrations.AddField(
            model_name='report',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventRecord.assignment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_images/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventRecord.report')),
            ],
        ),
        migrations.DeleteModel(
            name='ReportFile',
        ),
    ]
