# Generated by Django 5.0.6 on 2024-06-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0009_rename_notes_report_content_remove_report_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
