# Generated by Django 5.0.6 on 2024-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0010_alter_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='message',
            field=models.TextField(max_length=225),
        ),
    ]
