# Generated by Django 5.0.6 on 2024-06-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0011_alter_assignment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
