# Generated by Django 5.0.6 on 2024-06-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0012_remove_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(default='unknown', upload_to='report_images/'),
        ),
        migrations.DeleteModel(
            name='ReportImage',
        ),
    ]
