# Generated by Django 5.0.6 on 2024-06-19 14:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0014_alter_report_image_alter_report_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
