# Generated by Django 5.0.6 on 2024-06-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0015_alter_report_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('disabled', 'Disabled')], default='active', max_length=50),
        ),
    ]
