# Generated by Django 5.0.6 on 2024-07-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0018_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
