# Generated by Django 5.0.6 on 2024-07-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0019_eventcategory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('disabled', 'Disabled')], max_length=50),
        ),
    ]
