# Generated by Django 5.0.6 on 2024-07-24 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0022_notification'),
        ('employee', '0006_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EventRecord.assignment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
    ]
