# Generated by Django 5.0.6 on 2024-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_staff_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_ID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
