# Generated by Django 5.0.6 on 2024-05-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
    ]
